const GAME_INFO = {
  name: "AI Adventure",
  description:
    "AI Adventure is a role playing game entirely generated by AI. It is a game that is only limited by your imagination.",
};

export default GAME_INFO;
