export const levels = [
  "Nomadic Trailblazer",
  "Crypt Keeper",
  "Legendary Hero",
  "Enchanted Explorer",
  "Brave Voyager",
  "Questing Crusader",
  "Realm Ranger",
  "Exalted Adventurer",
  "Astral Artificer",
  "Mystical Trailblazer",
  "Mythical Maven",
  "Rune Reveler",
  "Timeless Traveler",
  "Elemental Eradicator",
  "Dreamwalker",
  "Celestial Cartomancer",
  "Abyssal Archon",
  "Multiversal Marveler",
  "Void Vagabond",
  "Chaos Commander",
  "Destiny's Chosen",
  "Arcane Archaeologist",
  "Ethereal Emissary",
  "Celestial Sentinel",
  "Dimensional Delver",
  "Paradox Pursuer",
  "Reality Weaver",
  "Cosmic Cartographer",
  "Eldritch Enforcer",
  "Planar Paragon",
  "Legendary Lorekeeper",
  "Eternal Nomad",
  "Astral Anomaly Arbiter",
  "World Shaper",
  "Fatebender",
  "Celestial Wayfarer",
  "Elemental Sage",
  "Starry Seeker",
  "Mythos Mariner",
  "Quantum Quester",
  "Chaos Conductor",
  "Dreamweaver",
  "Reality Architect",
  "Astral Sage",
  "Time-Storm Navigator",
  "Destiny's Oracle",
  "Epoch Explorer",
  "Cosmic Catalyst",
  "Void Voyager",
  "Planeswalker",
  "Paradox Prophet",
  "Dreamworld Diviner",
  "Rune Warden",
  "Eternal Guardian",
  "Astral Seeker",
  "Legend Liberator",
  "Elemental Exemplar",
  "Multiverse Maven",
  "Void Warden",
  "Time-Thief",
  "Chaos Conjurer",
  "Celestial Sage",
  "Dreambound Voyager",
  "Ethereal Exile",
  "Abyssal Artificer",
  "Planar Pilgrim",
  "Quantum Explorer",
  "Reality Reaver",
  "Celestial Sovereign",
  "Eldritch Arbiter",
  "Astral Cartographer",
  "Paradoxical Pioneer",
  "Time-Warped Traveler",
  "Mythos Minstrel",
  "Destiny's Harbinger",
  "Cosmic Conductor",
  "Void Vortexer",
  "Elemental Enigma",
  "Dreamweaver",
  "Rune Ritualist",
  "Astral Sage",
  "Celestial Chronomancer",
  "Time-Walker",
  "Epoch Emissary",
  "Planar Protector",
  "Multiversal Marshall",
  "Void Voyager",
  "Chaos Conjurer",
  "Reality Remaker",
  "Mythic Maven",
  "Eldritch Enchanter",
  "Celestial Sentinel",
  "Starborne Seeker",
  "Destiny's Oracle",
  "Elemental Archon",
  "Astral Artisan",
  "Rune Relic Hunter",
  "Timeless Nomad",
  "Abyssal Arbiter",
  "Eternal Hero",
];
