import {
  CircleDollarSignIcon,
  FingerprintIcon,
  VenetianMaskIcon,
  WandIcon,
} from "lucide-react";
import { TypographyMuted } from "../ui/typography/TypographyMuted";
import SectionContainer from "./section-container";

const features = [
  {
    name: "On the fly generation",
    description: "Story, images, and audio are generated by AI on the fly.",
    emoji: "🪄",
    icon: WandIcon,
  },
  {
    name: "Swappable Models",
    description:
      "Bring your own LLMs, connect your own SD LoRAs -- and let users create with custom prompts.",
    emoji: "🎭",
    icon: VenetianMaskIcon,
  },
  {
    name: "Payment Ready",
    description:
      "Stripe Integration is built in. Turn this server into a business for your site.",
    emoji: "💰",
    icon: CircleDollarSignIcon,
  },
  {
    name: "Simple Authentication",
    description:
      "Uses Clerk for simple authentication in development and production.",
    emoji: "🔑",
    icon: FingerprintIcon,
  },
];

export default function OpenSource() {
  return (
    <SectionContainer>
      <div className="mx-auto max-w-7xl px-6 lg:px-8">
        <div className="mx-auto max-w-2xl lg:text-center">
          <h2 className="text-base font-semibold leading-7 text-indigo-400">
            Make your own
          </h2>
          <p className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">
            Completely open source
          </p>
          <TypographyMuted className="mt-6 text-lg leading-8 ">
            AI Adventure is completely open source. You can find the code on our
            GitHub page. Come help us build the future of AI storytelling.
          </TypographyMuted>
        </div>
        <div className="mx-auto mt-16 max-w-2xl sm:mt-20 lg:mt-24 lg:max-w-4xl">
          <dl className="grid max-w-xl grid-cols-1 gap-x-8 gap-y-10 lg:max-w-none lg:grid-cols-2 lg:gap-y-16">
            {features.map((feature) => (
              <div key={feature.name} className="relative pl-16">
                <dt className="text-base font-semibold leading-7">
                  <div className="absolute left-0 top-0 flex h-10 w-10 items-center justify-center rounded-lg bg-indigo-600">
                    <feature.icon
                      className="h-6 w-6 text-white"
                      aria-hidden="true"
                    />
                  </div>
                  {feature.name}
                </dt>
                <dd className="mt-2 text-base leading-7 text-muted-foreground">
                  {feature.description}
                </dd>
              </div>
            ))}
          </dl>
        </div>
      </div>
    </SectionContainer>
  );
}
