"use client";
import { getGameState } from "@/lib/game/game-state.client";
import { useEffect, useState } from "react";
import { useRecoilValue } from "recoil";
import { recoilGameState } from "../recoil-provider";
import { Button } from "../ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "../ui/dialog";
import { Skeleton } from "../ui/skeleton";
import { TypographyLarge } from "../ui/typography/TypographyLarge";
import { TypographyMuted } from "../ui/typography/TypographyMuted";

export const WelcomeModal = () => {
  const gameState = useRecoilValue(recoilGameState);
  const [isOpen, setIsOpen] = useState(false);
  const [profilePic, setProfilePic] = useState<string | null>(null);
  const [imageLoaded, setImageLoaded] = useState(false);

  useEffect(() => {
    const loadProfilePic = async () => {
      setImageLoaded(false);
      const gs = await getGameState();
      console.log("gs", gs);
      if (gs && gs.profile_image_url) {
        setProfilePic(gs.profile_image_url);
        setImageLoaded(true);
      }
    };
    const interval = setInterval(() => {
      if (profilePic) return;
      loadProfilePic();
    }, 1000);
    return () => {
      clearInterval(interval);
    };
  }, [profilePic]);

  useEffect(() => {
    if (gameState?.quests?.length > 0) {
      return;
    }
    // Check if the user has already seen this modal.
    const welcomeModalSeen = localStorage.getItem("welcomeModalSeen");
    if (!welcomeModalSeen) {
      setIsOpen(true);
      localStorage.setItem("welcomeModalSeen", "true");
    }
  }, [gameState?.quests?.length]);

  return (
    <Dialog open={isOpen} onOpenChange={(open) => setIsOpen(open)}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>
            <span className="mr-2">👋</span>Welcome to AI Adventure!
          </DialogTitle>
          <div className="flex flex-col gap-4">
            <div className="flex items-center flex-col justify-center mt-4 p-2">
              <div className="w-full flex items-center flex-col justify-center p-4 border border-foreground/20 rounded-md shadow-lg dark:bg-black bg-white">
                <TypographyLarge>{gameState?.player?.name}</TypographyLarge>
                <TypographyMuted>
                  {gameState?.player?.background}
                </TypographyMuted>
                <div className="mt-2">
                  {imageLoaded && profilePic ? (
                    <img
                      className="w-24 h-24 rounded-full"
                      src={profilePic}
                      alt="Generated profile pic"
                    />
                  ) : (
                    <Skeleton className="w-24 h-24 rounded-full" />
                  )}
                </div>
              </div>
            </div>
            <TypographyMuted className="text-base">
              AI Adventure is a open-ended adventure game where everything is
              generated by AI and powered by{" "}
              <a
                className="text-blue-500"
                href="https://www.steamship.com/"
                target="_blank"
              >
                Steamship
              </a>
              . Explore your own unique world by going on adventures, collecting
              & trading items, and chatting with NPCs.
            </TypographyMuted>

            <TypographyMuted className="text-base">
              Every story, image, item, and sound is generated by AI. That means
              no two players will have the same experience.
            </TypographyMuted>
            <Button onClick={() => setIsOpen(false)}>Let&apos;s go!</Button>
          </div>
        </DialogHeader>
      </DialogContent>
    </Dialog>
  );
};
