"use client";
import { useEffect, useState } from "react";
import { useRecoilValue } from "recoil";
import { recoilGameState } from "../recoil-provider";
import { Button } from "../ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "../ui/dialog";
import { TypographyMuted } from "../ui/typography/TypographyMuted";

export const WelcomeModal = () => {
  const gameState = useRecoilValue(recoilGameState);
  const [isOpen, setIsOpen] = useState(false);

  useEffect(() => {
    if (gameState?.quests?.length > 0) {
      return;
    }
    // Check if the user has already seen this modal.
    const welcomeModalSeen = localStorage.getItem("welcomeModalSeen");
    if (!welcomeModalSeen) {
      setIsOpen(true);
      localStorage.setItem("welcomeModalSeen", "true");
    }
  }, [gameState?.quests?.length]);

  return (
    <Dialog open={isOpen} onOpenChange={(open) => setIsOpen(open)}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>
            <span className="mr-2">👋</span>Welcome to AI Adventure!
          </DialogTitle>
          <div className="flex flex-col gap-4">
            <TypographyMuted className="text-base mt-4">
              AI Adventure is a open-ended adventure game where everything is
              generated by AI and powered by{" "}
              <a
                className="text-blue-500"
                href="https://www.steamship.com/"
                target="_blank"
              >
                Steamship
              </a>
              . Explore your own unique world by going on adventures, collecting
              & trading items, and chatting with NPCs.
            </TypographyMuted>

            <TypographyMuted className="text-base">
              Every story, image, item, and sound is generated by AI. That means
              no two players will have the same experience.
            </TypographyMuted>
            <Button onClick={() => setIsOpen(false)}>Let&apos;s go!</Button>
          </div>
        </DialogHeader>
      </DialogContent>
    </Dialog>
  );
};
